/*
* generated by Xtext
*/
package org.xtext.cfgdsl;

import ConfiguratorPackage.impl.ConfiguratorPackagePackageImpl;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CfgDslStandaloneSetup extends CfgDslStandaloneSetupGenerated{

	public static void doSetup() {
		new CfgDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
	
	@Override
	public Injector createInjectorAndDoEMFRegistration() {
               
		ConfiguratorPackagePackageImpl.init(); 
		org.eclipse.xtext.common.TerminalsStandaloneSetup.doSetup();

		Injector injector = createInjector();
		register(injector);
		return injector;
	}
}

