/*
 * generated by Xtext
 */
package org.xtext.cfgdsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CfgDslRuntimeModule extends org.xtext.cfgdsl.AbstractCfgDslRuntimeModule {

}
