/**
 * generated by Xtext
 */
package org.xtext.cfgdsl.generator;

import ConfiguratorPackage.Root;
import com.google.common.collect.Iterables;
import java.util.function.Consumer;
import org.eclipse.emf.common.util.TreeIterator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.generator.IGenerator;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.xtext.cfgdsl.generator.JsonConverter;

/**
 * Generates code from your model files on save.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#TutorialCodeGeneration
 */
@SuppressWarnings("all")
public class CfgDslGenerator implements IGenerator {
  public static CharSequence compileToJava(final Root it) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field constraintMap is undefined for the type CfgDslGenerator");
  }
  
  /**
   * class Validator {
   * 
   * public static boolean validate(List<Assignment> assignments) {
   * boolean valid = true;
   * Map<String, Assignment> map = new HashMap<String, Assignment>();
   * 
   * // Check the types of the assignments are well typed
   * for(Assignment a : assignments) {
   * if(a.getValue() instanceof StringValue)
   * valid = valid && (a.getParameter().getType().equals(((StringValue)a.getValue()).getType()));
   * if(a.getValue() instanceof IntegerValue)
   * valid = valid && (a.getParameter().getType().equals(((IntegerValue)a.getValue()).getType()));
   * if(a.getValue() instanceof BooleanValue)
   * valid = valid && (a.getParameter().getType().equals(((BooleanValue)a.getValue()).getType()));
   * 
   * map.put(a.getParameter().getName(), a);
   * }
   * if(!valid)
   * return false;
   * 
   * ...Start the validation
   * 
   * return true;
   * }
   * 
   * 
   * 
   * }
   */
  public static String compileToJson(final Root it) {
    return JsonConverter.generate(it);
  }
  
  public void doGenerate(final Resource resource, final IFileSystemAccess fsa) {
    TreeIterator<EObject> _allContents = resource.getAllContents();
    Iterable<EObject> _iterable = IteratorExtensions.<EObject>toIterable(_allContents);
    Iterable<Root> _filter = Iterables.<Root>filter(_iterable, Root.class);
    final Consumer<Root> _function = new Consumer<Root>() {
      public void accept(final Root it) {
        final String fname = "Mikkel";
        CharSequence _compileToJava = CfgDslGenerator.compileToJava(it);
        fsa.generateFile((("MDDPConfigurator/" + fname) + ".java"), _compileToJava);
      }
    };
    _filter.forEach(_function);
  }
}
