/**
 * generated by Xtext
 */
package org.xtext.cfgdsl.ui.contentassist;

import org.xtext.cfgdsl.ui.contentassist.AbstractCfgDslProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class CfgDslProposalProvider extends AbstractCfgDslProposalProvider {
}
