/**
 * generated by Xtext
 */
package org.xtext.cfgdsl.serializer;

import org.xtext.cfgdsl.serializer.AbstractCfgDslSyntacticSequencer;

@SuppressWarnings("all")
public class CfgDslSyntacticSequencer extends AbstractCfgDslSyntacticSequencer {
}
