/**
 * generated by Xtext
 */
package org.xtext.cfgdsl.serializer;

import org.xtext.cfgdsl.serializer.AbstractCfgDslSemanticSequencer;

@SuppressWarnings("all")
public class CfgDslSemanticSequencer extends AbstractCfgDslSemanticSequencer {
}
