/*
* generated by Xtext
*/
package org.xtext.cfgdsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.cfgdsl.services.CfgDslGrammarAccess;

public class CfgDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CfgDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.cfgdsl.parser.antlr.internal.InternalCfgDslParser createParser(XtextTokenStream stream) {
		return new org.xtext.cfgdsl.parser.antlr.internal.InternalCfgDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Root";
	}
	
	public CfgDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CfgDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
