/*
 * generated by Xtext
 */
package org.xtext.cfgdsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.cfgdsl.ui.internal.CfgDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CfgDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CfgDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CfgDslActivator.getInstance().getInjector(CfgDslActivator.ORG_XTEXT_CFGDSL_CFGDSL);
	}
	
}
